# Generated by Django 4.2.30 on 2026-09-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('total_students', models.IntegerField(default=0)),
                ('expected_headcount', models.FloatField(default=0)),
                ('actual_headcount', models.IntegerField(default=0)),
                ('headcount_accuracy', models.FloatField(default=0)),
                ('expected_undecided', models.FloatField(default=0)),
                ('program_results', models.JSONField(default=list)),
            ],
        ),
    ]
