# Generated by Django 4.2.30 on 2026-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='headcount_max_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='headcount_min_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='model_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='overall_barrier_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='overall_program_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='pursue_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='support_results',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='top_barrier',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='top_program',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
